# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true
gems: [jekyll-paginate]

# edit here to achieve your personal greatness
url: http://snakeshawn.github.io/
baseurl: /
title: Zhang Xu
author: Zhang Xu
description: Personal blog and resume
avatar: profile.png
email: snakeshawnzhang@gmail.com
github: snakeshawn
twitter: Snake_Shawn
linkedin: username
disqus: username
google_analytics: UA-69391421-1
